sudo: required
services:
 - docker

before_install:
 - docker build -t tutus/frontend -f Dockerfile . 

script:
  - docker run -e CI=true tutus/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend2"
  env: "Frontend2-env"
  bucket_name: "elasticbeanstalk-us-east-2-874751794732"
  bucket_path: "frontend2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY 
